'use strict';

export const colors =
    [
        { label: 'Aquamarine', value: 'AQUAMARINE' },
        { label: 'Antique white', value: 'ANTIQUE WHITE' },
        { label: 'Beige', value: 'BEIGE' },
        { label: 'Black', value: 'BLACK' },
        { label: 'Blue', value: 'BLUE' },
        { label: 'Blue violet', value: 'BLUE VIOLET' },
        { label: 'Brick', value: 'BRICK' },
        { label: 'Brown', value: 'BROWN' },
        { label: 'Burnt sienna', value: 'BURNT SIENNA' },
        { label: 'Burnt umber', value: 'BURNT UMBER' },
        { label: 'Cadet blue', value: 'CADET BLUE' },
        { label: 'Chocolate', value: 'CHOCOLATE' },
        { label: 'Cobalt', value: 'COBALT' },
        { label: 'Coral', value: 'CORAL' },
        { label: 'Cyan', value: 'CYAN' },
        { label: 'Dimgray', value: 'DIMGRAY' },
        { label: 'Emerald green', value: 'EMERALD GREEN' },
        { label: 'Firebrick', value: 'FIREBRICK' },
        { label: 'Flesh', value: 'FLESH' },
        { label: 'Forest green', value: 'FOREST GREEN' },
        { label: 'Gold', value: 'GOLD' },
        { label: 'Goldenrod', value: 'GOLDENROD' },
        { label: 'Gray', value: 'GRAY' },
        { label: 'Green', value: 'GREEN' },
        { label: 'Green yellow', value: 'GREEN YELLOW' },
        { label: 'Honeydew', value: 'HONEYDEW' },
        { label: 'Hot pink', value: 'HOT PINK' },
        { label: 'Indian red', value: 'INDIAN RED' },
        { label: 'Indigo', value: 'INDIGO' },
        { label: 'Ivory', value: 'IVORY' },
        { label: 'Ivory black', value: 'IVORY BLACK' },
        { label: 'Kelly green', value: 'KELLY GREEN' },
        { label: 'Khaki', value: 'KHAKI' },
        { label: 'Lavender', value: 'LAVENDER' },
        { label: 'Lime green', value: 'LIME GREEN' },
        { label: 'Magenta', value: 'MAGENTA' },
        { label: 'Maroon', value: 'MAROON' },
        { label: 'Melon', value: 'MELON' },
        { label: 'Midnight blue', value: 'MIDNIGHT BLUE' },
        { label: 'Mint', value: 'MINT' },
        { label: 'Navy', value: 'NAVY' },
        { label: 'Olive', value: 'OLIVE' },
        { label: 'Olive drab', value: 'OLIVE DRAB' },
        { label: 'Orange', value: 'ORANGE' },
        { label: 'Orange red', value: 'ORANGE RED' },
        { label: 'Orchid', value: 'ORCHID' },
        { label: 'Pink', value: 'PINK' },
        { label: 'Powder blue', value: 'POWDER BLUE' },
        { label: 'Purple', value: 'PURPLE' },
        { label: 'Raspberry', value: 'RASPBERRY' },
        { label: 'Red', value: 'RED' },
        { label: 'Royal blue', value: 'ROYAL BLUE' },
        { label: 'Salmon', value: 'SALMON' },
        { label: 'Sandy brown', value: 'SANDY BROWN' },
        { label: 'Sea green', value: 'SEA GREEN' },
        { label: 'Sepia', value: 'SEPIA' },
        { label: 'Sienna', value: 'SIENNA' },
        { label: 'Silver', value: 'SILVER' },
        { label: 'Sky blue', value: 'SKY BLUE' },
        { label: 'Slateblue', value: 'SLATEBLUE' },
        { label: 'Slate gray', value: 'SLATE GRAY' },
        { label: 'Spring green', value: 'SPRING GREEN' },
        { label: 'Steel blue', value: 'STEEL BLUE' },
        { label: 'Tan', value: 'TAN' },
        { label: 'Teal', value: 'TEAL' },
        { label: 'Thistle', value: 'THISTLE' },
        { label: 'Tomato', value: 'TOMATO' },
        { label: 'Turquoise', value: 'TURQUOISE' },
        { label: 'Violet', value: 'VIOLET' },
        { label: 'Violet red', value: 'VIOLET RED' },
        { label: 'White', value: 'WHITE' },
        { label: 'Yellow', value: 'YELLOW' }
    ];