'use strict';

export const species =
    [
        { id: 'Acetone', value: 'acetone', mw: 58.07914, formula: 'C3H6O', sigmalj: 4.6, epsilonklj: 560.2, liquid: 'Y', radcal: 'MMA', editable: false },
        { id: 'Acetylene', value: 'acetylene', mw: 26.03728, formula: 'C2H2', sigmalj: 4.033, epsilonklj: 231.8, liquid: 'N', radcal: 'PROPYLENE', editable: false },
        { id: 'Acrolein', value: 'acrolein', mw: 56.06326, formula: 'C3H4O', sigmalj: 4.549, epsilonklj: 576.7, liquid: 'Y', radcal: 'MMA', editable: false },
        { id: 'Ammonia', value: 'ammonia', mw: 17.03052, formula: 'NH3', sigmalj: 2.9, epsilonklj: 558.3, liquid: 'Y', radcal: '', editable: false },
        { id: 'Argon', value: 'argon', mw: 39.948, formula: 'Ar', sigmalj: 3.42, epsilonklj: 124, liquid: 'Y', radcal: '', editable: false },
        { id: 'Benzene', value: 'benzene', mw: 78.11184, formula: 'C6H6', sigmalj: 5.349, epsilonklj: 412.3, liquid: 'Y', radcal: 'TOLUENE', editable: false },
        { id: 'Butane', value: 'butane', mw: 58.1222, formula: 'C4H10', sigmalj: 4.687, epsilonklj: 531.4, liquid: 'Y', radcal: 'PROPANE', editable: false },
        { id: 'Carbon', value: 'carbon', mw: 12.0107, formula: 'C', sigmalj: 2.94, epsilonklj: 74.8, liquid: 'N', radcal: '', editable: false },
        { id: 'Carbon dioxide', value: 'carbon dioxide', mw: 44.0095, formula: 'CO2', sigmalj: 3.941, epsilonklj: 195.2, liquid: 'N', radcal: 'CARBON DIOXIDE', editable: false },
        { id: 'Carbon monoxide', value: 'carbon monoxide', mw: 28.0101, formula: 'CO', sigmalj: 3.69, epsilonklj: 91.7, liquid: 'Y', radcal: 'CARBON MONOXIDE', editable: false },
        { id: 'Chlorine', value: 'chlorine', mw: 70.906, formula: 'Cl2', sigmalj: 4.217, epsilonklj: 316, liquid: 'Y', radcal: '', editable: false },
        { id: 'Dodecane', value: 'dodecane', mw: 170.33484, formula: 'C12H26', sigmalj: 4.701, epsilonklj: 205.78, liquid: 'Y', radcal: 'N-HEPTANE', editable: false },
        { id: 'Ethane', value: 'ethane', mw: 30.06904, formula: 'C2H6', sigmalj: 4.443, epsilonklj: 215.7, liquid: 'Y', radcal: 'ETHANE', editable: false },
        { id: 'Ethanol', value: 'ethanol', mw: 46.06844, formula: 'C2H5OH', sigmalj: 4.53, epsilonklj: 362.6, liquid: 'Y', radcal: 'METHANOL', editable: false },
        { id: 'Ethylene', value: 'ethylene', mw: 28.05316, formula: 'C2H4', sigmalj: 4.163, epsilonklj: 224.7, liquid: 'Y', radcal: 'ETHYLENE', editable: false },
        { id: 'Formaldehyde', value: 'formaldehyde', mw: 30.02598, formula: 'CH2O', sigmalj: 3.626, epsilonklj: 481.8, liquid: 'Y', radcal: 'METHANOL', editable: false },
        { id: 'Helium', value: 'helium', mw: 4.002602, formula: 'He', sigmalj: 2.551, epsilonklj: 10.22, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen', value: 'hydrogen', mw: 2.01588, formula: 'H2', sigmalj: 2.827, epsilonklj: 59.7, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen atom', value: 'hydrogen atom', mw: 1.00794, formula: 'H', sigmalj: 2.31, epsilonklj: 123.6, liquid: 'N', radcal: '', editable: false },
        { id: 'Hydrogen bromide', value: 'hydrogen bromide', mw: 80.91194, formula: 'HBr', sigmalj: 3.353, epsilonklj: 449, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen chloride', value: 'hydrogen chloride', mw: 36.46094, formula: 'HCl', sigmalj: 3.339, epsilonklj: 344.7, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen cyanide', value: 'hydrogen cyanide', mw: 27.02534, formula: 'HCN', sigmalj: 3.63, epsilonklj: 569.1, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen fluoride', value: 'hydrogen fluoride', mw: 20.006343, formula: 'HF', sigmalj: 3.148, epsilonklj: 330, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydrogen peroxide', value: 'hydrogen peroxide', mw: 34.01468, formula: 'H2O2', sigmalj: 3.02, epsilonklj: 106.5, liquid: 'Y', radcal: '', editable: false },
        { id: 'Hydroperoxy radical', value: 'hydroperoxy radical', mw: 33.00674, formula: 'HO2', sigmalj: 3.02, epsilonklj: 106.5, liquid: 'N', radcal: '', editable: false },
        { id: 'Hydroxyl radical', value: 'hydroxyl radical', mw: 17.00734, formula: 'OH', sigmalj: 2.66, epsilonklj: 92.1, liquid: 'N', radcal: '', editable: false },
        { id: 'Isopropanol', value: 'isopropanol', mw: 60.09502, formula: 'C3H7OH', sigmalj: 4.549, epsilonklj: 576.7, liquid: 'Y', radcal: 'METHANOL', editable: false },
        { id: 'Lj air', value: 'lj air', mw: 28.85476, formula: '', sigmalj: 3.711, epsilonklj: 78.6, liquid: 'N', radcal: '', editable: false },
        { id: 'Methane', value: 'methane', mw: 16.04246, formula: 'CH4', sigmalj: 3.758, epsilonklj: 148.6, liquid: 'Y', radcal: 'METHANE', editable: false },
        { id: 'Methanol', value: 'methanol', mw: 32.04186, formula: 'CH2OH', sigmalj: 3.626, epsilonklj: 481.8, liquid: 'Y', radcal: 'METHANOL', editable: false },
        { id: 'N-decane', value: 'n-decane', mw: 142.28168, formula: 'C10H22', sigmalj: 5.233, epsilonklj: 226.46, liquid: 'Y', radcal: 'N-HEPTANE', editable: false },
        { id: 'N-heptane', value: 'n-heptane', mw: 100.20194, formula: 'C7H16', sigmalj: 4.701, epsilonklj: 205.75, liquid: 'Y', radcal: 'N-HEPTANE', editable: false },
        { id: 'N-hexane', value: 'n-hexane', mw: 86.17536, formula: 'C6H12', sigmalj: 5.949, epsilonklj: 399.3, liquid: 'Y', radcal: 'N-HEPTANE', editable: false },
        { id: 'N-octane', value: 'n-octane', mw: 114.22852, formula: 'C8H18', sigmalj: 4.892, epsilonklj: 231.16, liquid: 'Y', radcal: 'N-HEPTANE', editable: false },
        { id: 'Nitric oxide', value: 'nitric oxide', mw: 30.0061, formula: 'NO', sigmalj: 3.492, epsilonklj: 116.7, liquid: 'Y', radcal: '', editable: false },
        { id: 'Nitrogen', value: 'nitrogen', mw: 28.0134, formula: 'N2', sigmalj: 3.798, epsilonklj: 71.4, liquid: 'Y', radcal: '', editable: false },
        { id: 'Nitrogen atom', value: 'nitrogen atom', mw: 14.0067, formula: 'N', sigmalj: 2.66, epsilonklj: 92.1, liquid: 'N', radcal: '', editable: false },
        { id: 'Nitrogen dioxide', value: 'nitrogen dioxide', mw: 46.055, formula: 'NO2', sigmalj: 3.992, epsilonklj: 204.88, liquid: 'Y', radcal: '', editable: false },
        { id: 'Nitrous oxide', value: 'nitrous oxide', mw: 44.0128, formula: 'N2O', sigmalj: 3.828, epsilonklj: 232.4, liquid: 'Y', radcal: '', editable: false },
        { id: 'Oxygen', value: 'oxygen', mw: 31.9988, formula: 'O2', sigmalj: 3.467, epsilonklj: 106.7, liquid: 'Y', radcal: '', editable: false },
        { id: 'Oxygen atom', value: 'oxygen atom', mw: 15.9994, formula: 'O', sigmalj: 2.66, epsilonklj: 92.1, liquid: 'N', radcal: '', editable: false },
        { id: 'Propane', value: 'propane', mw: 44.09562, formula: 'C3H8', sigmalj: 5.118, epsilonklj: 237.1, liquid: 'Y', radcal: 'PROPANE', editable: false },
        { id: 'Propylene', value: 'propylene', mw: 42.07974, formula: 'C3H6', sigmalj: 4.678, epsilonklj: 298.9, liquid: 'Y', radcal: 'PROPYLENE', editable: false },
        { id: 'Soot', value: 'soot', mw: 10.91042, formula: 'C0.9H0.1', sigmalj: 3.798, epsilonklj: 71.4, liquid: 'N', radcal: 'SOOT', editable: false },
        { id: 'Sulfur dioxide', value: 'sulfur dioxide', mw: 64.0638, formula: 'SO2', sigmalj: 4.112, epsilonklj: 335.4, liquid: 'Y', radcal: '', editable: false },
        { id: 'Sulfur hexafluoride', value: 'sulfur hexafluoride', mw: 146.055419, formula: 'SF6', sigmalj: 5.128, epsilonklj: 146, liquid: 'N', radcal: '', editable: false },
        { id: 'Toluene', value: 'toluene', mw: 92.13842, formula: 'C6H5CH3', sigmalj: 5.698, epsilonklj: 480, liquid: 'Y', radcal: 'TOLUENE', editable: false },
        { id: 'Water vapor', value: 'water vapor', mw: 18.01528, formula: 'H2O', sigmalj: 2.641, epsilonklj: 809.1, liquid: 'Y', radcal: 'WATER VAPOR', editable: false }
    ];