# Define internal network for AAMKS containers
networks:
  aamks_network:

services:
  # Apache web-server hosting GUI
  web:
    build:
      context: ./apache2
    restart: always
    networks:
      - aamks_network
    ports:
      - "8080:80"
      #- "443:443"
    depends_on:
      - db
    user: "33:33"                                         # www-data in the image
    volumes:
      - aamks_users:/home/aamks_users:rw                  # aamks users read-write
      - ./apache2/aamks-apache2.conf:/etc/apache2/apache2.conf    # web-server configuration
      - ${HOST_AAMKS_PATH}/gui:/usr/local/aamks/gui:rw          # mostly gui code is required by web-server
      - ${HOST_AAMKS_PATH}/inc.json:/usr/local/aamks/inc.json:rw  # settings for Apainter
      - ${HOST_AAMKS_PATH}/evac/config.json:/usr/local/aamks/evac/config.json:rw  # default project settings
    # Variables from .env (host envvars will take precedence by default)
    environment:
      - AAMKS_PATH=/usr/local/aamks    # path to AAMKS code (with gui only) in the image
      - AAMKS_USE_MAIL=${AAMKS_USE_MAIL}
      - AAMKS_MAIL_PASSWORD=${AAMKS_MAIL_PASSWORD}
      - AAMKS_MAIL_SENDER=${AAMKS_MAIL_SENDER} 
      - AAMKS_DB=${AAMKS_DB}
      - AAMKS_SERVER=${AAMKS_SERVER}
      - AAMKS_PG_PASS=${AAMKS_PG_PASS} 
      - AAMKS_WORKER=${AAMKS_WORKER}
      - AAMKS_SALT=${AAMKS_SALT}
      - AAMKS_REDIS_PASS=${AAMKS_REDIS_PASS}

  # PostgreSQL is main database service for AAMKS
  # all settings are imported from ./postgres/init.sql at the FIRST launch only
  db:
    image: postgres:14.5
    restart: always
    networks:
      - aamks_network
    ports:
      - "5432:5432"
    environment:
      - AAMKS_SERVER="aamks-web"
      - POSTGRES_USER=aamks 
      - POSTGRES_PASSWORD=${AAMKS_PG_PASS} 
      - POSTGRES_DATABASE=aamks 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${HOST_AAMKS_PATH}/installer/simulations.csv:/usr/local/aamks/installer/simulations.csv

  # Redis is used to queuing and task scheduling
  # integrating with existing SLURM configurations will require more attention
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"   # link container port to host port
    command: redis-server --save 20 1 --loglevel warning --requirepass ${AAMKS_REDIS_PASS}
    volumes:
      - rddata:/data


  # AAMKS service that basically executes python scripts
  # To be deployed in the swarm
  app:
    build: 
      context: ./aamks
      additional_contexts:
        resources: ${HOST_AAMKS_PATH}
    depends_on:
      - db
      - web
    networks:
      - aamks_network
    volumes:
      - aamks_users:/home/aamks_users
    environment:
      - HOST_AAMKS_PATH=${HOST_AAMKS_PATH}

# Volumes - where data is stored, only aamks_repo and aamks_gui are binded to the host machine
volumes:
  pgdata:
  aamks_users:
  rddata:

