<?php 

$riskEntities=array(
	/*{{{*/
	
	'general'=>array(
		'project_name'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>'New Project',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'simulation_time'=>array(
			'type'=>'Real',
			'units'=>'s',
			'default'=>0,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>0, 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'number_of_simulations'=>array(
			'type'=>'Integer',
			'units'=>'',
			'default'=>5000,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>1, 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'3000',
					'maxExclusive'=>'20000',
				)
			)

		),
		'indoor_temp'=>array(
			'type'=>'Real',
			'units'=>'C',
			'default'=>20,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'elevation'=>array(
			'type'=>'Real',
			'units'=>'m',
			'default'=>0,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'indoor_pressure'=>array(
			'type'=>'Real',
			'units'=>'Pa',
			'default'=>101325,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>0, 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'humidity'=>array(
			'type'=>'Real',
			'units'=>'%',
			'default'=>40,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>0, 
					'maxInclusive'=>100, 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'building'=>array(
		'type'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>'',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'has_fire_detectors'=>array(
			'type'=>'Logical',
			'units'=>'',
			'default'=>false,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'has_sprinklers'=>array(
			'type'=>'Logical',
			'units'=>'',
			'default'=>false,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'has_trained_staff'=>array(
			'type'=>'Logical',
			'units'=>'',
			'default'=>false,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'has_dso'=>array(
			'type'=>'Logical',
			'units'=>'',
			'default'=>false,
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'alarming_level'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>'1',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'sprinklers'=>array(
		'activation_temp'=>array(
			'type'=>'Real',
			'units'=>'C',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'activation_obscuration'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),

		'rti'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'spray_density'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'detectors'=>array(
		'rti'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'activation_temp'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'activation_obscuration'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'mvent'=>array(
		'flow'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'begin_dropoff_pressure'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'zero_flow_pressure'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'initial_opening_fraction'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'filter_efficiency'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'materials'=>array(
		'thickness_wall'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'thickness_ceiling'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'thickness_floor'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)


	),
	'evacuation'=>array(
		'number_of_people'=>array(
			'type'=>'Integer',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'vertical_speed'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'horizontal_speed'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),


	),
	'window_open'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.11',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'plain_door_open'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.5',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.5',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'door_with_closer'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.14',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.86',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'electric_release_door'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.04',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.96',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'origin_of_fire'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.9',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.1',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_detectors_trigger_temp'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'337',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_detectors_failure'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.96',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.04',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'sprinkler_trigger_temp'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'337',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'3',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'sprinkler_failure'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.96',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.04',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'outdoor_temp'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'10',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'7',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'vertical_speed'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.8',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'horizontal_speed'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'1.2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'alarm_time'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'3.7',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.5',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_location'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'12',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_hrr'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'1200',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'9000',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_alpha'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.01',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.05',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_co'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.01',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.043',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'fire_soot'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.11',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.17',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'pre_movement'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'7.15',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.215',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)
	),
	'density_room'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'5',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'density_corridor'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'20',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'2',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'alpha_speed'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.706',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.069',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	),
	'beta_speed'=>array(
		'var1'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'-0.057',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'var2'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>'0.015',
			'help'=>'', 
			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		)

	)
/*}}}*/
);

?>
