<?php

$wizEntities=array(
/*{{{*/
	'MESH'=>array(
		'SIZE'=>array(
			'type'=>'Realtriplet',
			'units'=>'m',
			'default'=>array('0.1,0.1,0.1'),
			'help'=>'Mesh cell size help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'OPEN'=>array(
			'type'=>'LogicalSextuplet',
			'units'=>'',
			'default'=>array('false', 'false', 'false', 'false','false', 'false'),
			'help'=>'Mesh open help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				) 
			)

		)
	),
	'REAC'=>array(
		'RADCAL_ID'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('methane'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'SPEC'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('ethylene'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				) 
			)

		)
	),
	'RAMP'=>array(
		'TYPE'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('matl'),
			'help'=>'Ramp type help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxExclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'T'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'T help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'F'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'F help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)


	),
	'MATL'=>array(
		'CONDUCTIVITY_RAMP_F'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'CRF help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'SPECIFIC_HEAT_RAMP_F'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'F help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)

	),

	'SURF'=>array(
		'FRACTION'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('1'),
			'help'=>'Material fraction in layer help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'1.1', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)

		),
		'THICKNESS'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'Layer thickness help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'HRR_VALUE'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'HRRPUA help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'HRR'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'HRR help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'SPREAD_RATE'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'HRRPUA help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'ALPHA'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'HRRPUA help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),


	),
	'OBST'=>array(
		'ELEVATION'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'Elev help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)
	),
	'HOLE'=>array(
		'ELEVATION'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'Elev help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)
	),

	'VENT'=>array(
		'ELEVATION'=>array(
			'type'=>'Real',
			'units'=>'',
			'default'=>array('0'),
			'help'=>'Elev help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)
	),
	'HVAC'=>array(
		'DIRECTION'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('+x'),
			'help'=>'Direction help', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'0', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)
	),
	'DEVC'=>array(
		'TYPE'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('basic'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'GEOMETRICAL_TYPE'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('point'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)

	),
	'PROP'=>array(
		'TYPE'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('sprinkler'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'SMOKE_DETECTOR_MODEL'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('heskestad'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		),
		'SMOKE_DETECTOR_MODEL_TYPE'=>array(
			'type'=>'Character',
			'units'=>'',
			'default'=>array('cleary_ionization_i1'),
			'help'=>'', 
 			'pattern'=>'',
			'valid_ranges'=>array(
				array( 
					'minInclusive'=>'__', 
					'maxInclusive'=>'__', 
				) 
			),
			'reasonable_ranges'=>array(
				array( 
					'minExclusive'=>'__',
					'maxExclusive'=>'__',
				)
			)
		)

	)



/*}}}*/
);

?>
