from arun import aamks_run

aamks_run.delay(1)
aamks_run.delay(2)
aamks_run.delay(3)
aamks_run.delay(4)
aamks_run.delay(5)
aamks_run.delay(6)
aamks_run.delay(7)
aamks_run.delay(8)
aamks_run.delay(9)
aamks_run.delay(10)
aamks_run.delay(11)
aamks_run.delay(12)
aamks_run.delay(13)
aamks_run.delay(14)
aamks_run.delay(15)
aamks_run.delay(16)
aamks_run.delay(17)
aamks_run.delay(18)
aamks_run.delay(19)
aamks_run.delay(20)
