version: '3'

services:
  redis:
    image: redis:latest
    container_name: aamks_redis 
    restart: always
    ports:
      - '${AAMKS_SERVER:-127.0.0.1}:6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass hulakula
    volumes:
      - data-volume:/data

volumes:
  data-volume:
